theme: jekyll-theme-architect
title: "Digital Humanities Projects at the Penn Libraries: Home"
description: "The Digital Scholarship Team at the Penn Libraries offers a variety of partnership opportunities for students, faculty, and researchers interested in pursuing a digital project. Check out some of our current and past projects below!"
